name: Run Trading Bot

on:
  schedule:
    - cron: '0 16 * * *'  # Run at 19:00 EAT (UTC+3) every 350 minutes, adjusted from 14:57 EAT
  workflow_dispatch:

jobs:
  trade:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # Adjusted to 5 hours and 50 minutes
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true  # Ensure LFS files are downloaded

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test Telegram connection
      run: |
        echo "Testing Telegram connectivity..."
        response=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -d '{"chat_id":"'${{ secrets.TELEGRAM_CHAT_ID }}'", "text":"GitHub Actions connection test"}' \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage)
        
        if [[ $response == *"\"ok\":true"* ]]; then
          echo "✅ Telegram test successful!"
        else
          echo "❌ Telegram test failed: $response"
          exit 1
        fi

    - name: Debug ml_models folder
      run: |
        echo "Listing contents of ml_models folder:"
        ls -la /home/runner/work/surgeon-/surgeon-/ml_models/ || echo "ml_models folder not found or empty"

    - name: Run Trading Bot
      env:
        OANDA_ACCOUNT_ID: ${{ secrets.OANDA_ACCOUNT_ID }}
        OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
