name: Run Trading Bot
on:
  schedule:
    - cron: '50 */5 * * *'  # Run at minute 50 of every 5th hour
  workflow_dispatch:

jobs:
  trade:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test Telegram connection
      run: |
        echo "Testing Telegram connectivity..."
        response=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -d '{"chat_id":"'${{ secrets.TELEGRAM_CHAT_ID }}'", "text":"GitHub Actions connection test"}' \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage)
        
        if [[ $response == *"\"ok\":true"* ]]; then
          echo "✅ Telegram test successful!"
        else
          echo "❌ Telegram test failed: $response"
          exit 1
        fi
        
    - name: Run Trading Bot
      env:
        OANDA_ACCOUNT_ID: ${{ secrets.OANDA_ACCOUNT_ID }}
        OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
