name: Run Trading Bot
on:
  schedule:
    - cron: '0 */6 * * *'  # Restart every 6 hours
  workflow_dispatch:

jobs:
  trade:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Trading Bot
      env:
        OANDA_ACCOUNT_ID: ${{ secrets.OANDA_ACCOUNT_ID }}
        OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        PORT: 5000
      run: |
        python main.py