name: Run Trading Bot
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  trade:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas_ta  #==0.3.13  # Explicit installation first
        pip install -r requirements.txt
        
    - name: Verify models
      run: |
        ls -lh ml_models/
        echo "Models found: $(find ml_models/ -type f | wc -l)"
        
    - name: Run Trading Bot
      env:
        OANDA_ACCOUNT_ID: ${{ secrets.OANDA_ACCOUNT_ID }}
        OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TF_CPP_MIN_LOG_LEVEL: 3
      run: |
        python main.py
